---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-creds
  annotations:
    tekton.dev/git-0: github.com
spec:
  fromNamespace: tap-install
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: gitlab-creds
  annotations:
    tekton.dev/git-0: github.com
spec:
  fromNamespace: tap-install

